language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip  # required for py34 at least
  - pip install tox tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
